from config import Character

def encapsulate(character):
    lines = []
    
    # header
    lines.append(f"## ── {character.char_id} ──────────────────────────────────")
    lines.append(f"## {character.display_name}")
    lines.append(f"## shorthand: {character.shorthand}")
    lines.append(f"## generated by cerabellum ~ do not edit manually please <3")
    lines.append("")
    
    # layeredimage block
    lines.append(f"layeredimage {character.char_id}:")
    lines.append("")
    
    default_base_path = character._data['bases'].get(character.default_base)
    lines.append(f"    always \"{default_base_path}\"")
    lines.append("")
    
    # expression group
    default_expression = character._data.get('defaults', {}).get('expression')
    lines.append("    group expression:")
    for name, path in character._data['expressions'].items():
        if name == default_expression:
            lines.append(f"        attribute {name}    default \"{path}\"")
        else:
            lines.append(f"        attribute {name}    \"{path}\"")
    lines.append("")
    
    # eyes group
    default_eye = character._data.get('defaults', {}).get('eyes')
    lines.append("    group eyes:")
    for name, path in character._data['eyes'].items():
        if name == default_eye:
            lines.append(f"        attribute {name}    default \"{path}\"")
        else:
            lines.append(f"        attribute {name}    \"{path}\"")
    lines.append("")
    
       # ── character define ──────────────────────────────────────────────────────
    # if side_image is true, link the character define to the layeredimage
    # so Ren'Py automatically shows and hides the side image during dialogue
    lines.append("## ── character define ─────────────────────────────────────")
    colour = character.colour.replace("#", "")

    if character.side_image:
        lines.append(
            f"define {character.shorthand} = Character("
            f"\"{character.display_name}\", "
            f"color=\"#{colour}\", "
            f"image=\"{character.char_id}\")"
            f"  ## side image enabled — no hide calls needed ♡"
        )
    else:
        lines.append(
            f"define {character.shorthand} = Character("
            f"\"{character.display_name}\", "
            f"color=\"#{colour}\")"
        )
    lines.append("")

    return "\n".join(lines)
